apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  private.pem: {{ .Files.Get "keys/private.pem" | b64enc }}
  public.pem: {{ .Files.Get "keys/public.pem" | b64enc }}
