namespace: "istio-system"

repo: "https://github.com/MarkTerrious/Go_MSAProject_Infra"
curCluster: "https://kubernetes.default.svc"

appProjectName:
  infra: "argo-infra-project"

syncRetry:
  limit: 5
  backoffDuration: 5s
  backoffFactor: 2
  backoffMaxDuration: 3m
