# post-sa(post 서비스)만 post-db에 접근 가능하도록 제한
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: post-db-access
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: post-db
      app.kubernetes.io/component: primary
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/board-service/sa/post-sa"
              - "cluster.local/ns/board-db/sa/{{ .Values.serviceAccount.migration }}"
              # read replica 추가 시 replica -> primary replication 연결도 이 principals를 통과해야 하니 replica SA 추가 필요
