apiVersion: batch/v1
kind: Job
metadata:
  name: post-db-migration-job
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8}}
      {{- end }}
      containers:
        - name: goose-post
          image: ghcr.io/markterrious/goose-post:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: 
            - |
              MAX_RETRIES=50
              COUNT=0

              until pg_isready -h post-db -p 5432 -U postgresql; do 
                COUNT=$((COUNT + 1))
                if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
                  echo "Connect Fail (post-db)"
                  exit 1
                fi
                echo "wating for db... ($COUNT/$MAX_RETRIES)"
                sleep 2
              done

              goose -dir /migrations postgres \
              "host=post-db user=postgresql password=password dbname=gomsa sslmode=disable" up
      restartPolicy: OnFailure
  backoffLimit: 5  


          
