apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rhai.fullname" . }}-cfg
  labels:
    {{- include "rhai.labels" . | nindent 4 }}
data:
  router.rhai: |
    {{- .Files.Get "script/router.rhai" | nindent 4 }}
