apiVersion: v2
name: router
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: router
    alias: apollo-router
    repository: oci://ghcr.io/apollographql/helm-charts
    version: 2.14.0
