deploy_env: ""

namespace:
  service: "board-service"
  db: "board-db"
  gateway: "board-ingress"

# ambient mesh(mTLS/identity)에 편입시킬 네임스페이스에 붙일 라벨
ambientLabels:
  istio.io/dataplane-mode: ambient

appProjectName:
  db: "argo-database-project"
  app: "argo-application-project"
  gateway: "argo-gateway-project"
  preDeploy: "argo-pre-deploy-project"

repo: "https://github.com/MarkTerrious/Go_MSAProject_Infra"
curCluster: "https://kubernetes.default.svc"

syncRetry:
  limit: 5
  backoffDuration: 5s
  backoffFactor: 2
  backoffMaxDuration: 3m



