apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.fullname" . }}-svc
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "auth.selectorLabels" . | nindent 4 }}
