apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-jwt-role-binding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sa.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}
