apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "router.fullname" . }}-rhai-cfg
  labels:
    {{- include "router.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  router.rhai: |
    {{- .Files.Get "script/router.rhai" | nindent 4 }}
