apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.appProjectName.db }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: GoMSA Project About Deployment of db charts
  sourceRepos:
    - {{ .Values.repo }}
  destinations:
    - server: {{ .Values.curCluster }}
      namespace: {{ printf "%s-%s" .Values.namespace.db .Values.deploy_env | trimSuffix "-"}}
  
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.appProjectName.app }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: GoMSA Project About Deployment of app charts
  sourceRepos:
    - {{ .Values.repo }}
  destinations:
    - server: {{ .Values.curCluster }}
      namespace: {{ printf "%s-%s" .Values.namespace.service .Values.deploy_env | trimSuffix "-"}}
  namespaceResourceBlacklist:
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
