apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "gateway-%s" .Values.deploy_env | trimSuffix "-" }}
  labels:
    {{- include "argo-resource.labels" . | nindent 4 }}
spec:
  generators:
    - git:
        repoURL: {{ .Values.repo }}
        revision: main
        directories:
          - path: "charts/gateway/*"
  template:
    metadata:
      name: "{{ `{{path.basename}}` }}{{ if .Values.deploy_env }}-{{ .Values.deploy_env }}{{ end }}"
    spec:
      project: {{ printf "%s-%s" .Values.appProjectName.infra .Values.deploy_env | trimSuffix "-" }}
      source:
        repoURL: {{ .Values.repo }}
        targetRevision: main
        path: "{{ `{{path}}` }}"
        helm:
          valueFiles:
            - values.yaml
            {{- if eq .Values.deploy_env "prod"}}
            - values-prod.yaml
            {{- end}}
      destination:
        server: {{ .Values.curCluster }}
        namespace: {{ printf "%s-%s" .Values.namespace.gateway .Values.deploy_env | trimSuffix "-" }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: {{ .Values.syncRetry.limit }}
          backoff:
            duration: {{ .Values.syncRetry.backoffDuration }}
            factor: {{ .Values.syncRetry.backoffFactor }}
            maxDuration: {{ .Values.syncRetry.backoffMaxDuration }}
