# jwt Secret을 auth Pod가 볼륨으로 마운트하므로, auth와 같은 네임스페이스(default)에 배포.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pre-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  generators:
    - git:
        repoURL: {{ .Values.repo }}
        revision: main
        directories:
          - path: charts/pre-deploy/*
        allowEmpty: false
  template:
    metadata:
      name: "{{ `{{path.basename}}` }}"
    spec:
      project: {{ .Values.appProjectName.infra }}
      source:
        repoURL: {{ .Values.repo }}
        targetRevision: main
        path: "{{ `{{path}}` }}"
      destination:
        server: {{ .Values.curCluster }}
        namespace: {{ printf "%s-%s" .Values.namespace.app .Values.deploy_env | trimSuffix "-"}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: {{ .Values.syncRetry.limit }}
          backoff:
            duration: {{ .Values.syncRetry.backoffDuration }}
            factor: {{ .Values.syncRetry.backoffFactor }}
            maxDuration: {{ .Values.syncRetry.backoffMaxDuration }}
