apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ printf "%s-%s" .Values.appProjectName.infra .Values.deploy_env | trimSuffix "-" }}
  labels:
    {{- include "argo-resource.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: GoMSA Project About deployment of infra charts
  sourceRepos:
    - {{ .Values.repo }}
  destinations:
    - server: {{ .Values.curCluster }}
      namespace: {{ printf "%s-%s" .Values.namespace.gateway .Values.deploy_env | trimSuffix "-" }}
    - server: {{ .Values.curCluster }}
      namespace: {{ printf "%s-%s" .Values.namespace.service .Values.deploy_env | trimSuffix "-" }}

  # apiVersion: <Group>/<Version>
  # kind: <Resource Type>
  # 모든 그룹의 모든 리소스 타입들을 허용한다. 
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"