apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ printf "%s-%s" .Values.appProjectName.preDeploy .Values.deploy_env | trimSuffix "-" }}
  labels:
    {{- include "argo-resource.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: GoMSA Project About Deployment of pre-deploy charts (jwt keys/RBAC)
  sourceRepos:
    - {{ .Values.repo }}
  destinations:
    - server: {{ .Values.curCluster }}
      namespace: {{ printf "%s-%s" .Values.namespace.service .Values.deploy_env | trimSuffix "-" }}
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
