apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-writes
  namespace: istio-ingress
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway
  action: DENY
  rules:
    - to:
        - operation:
            paths: ["/api/v1/post*"]
            methods: ["POST", "PUT", "DELETE", "PATCH"]
      from:
        - source:
            notRequestPrincipals: ["*"]

# 해당 경로 /api/v1/post* 의 HTTP METHOD 차단
# 단 from 에서 jwt 없는 요청에 해당
# => 해당 주소 메서드 + jwt(x) = 차단
# => 해당 주소 메서드 + jwt(o) = 연결 허용
# => 해당 주소 메서드가 Get 이라면 = 연결 허용


