apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}    # gateway 이름
  annotations:
    networking.istio.io/service-type: NodePort
spec:
  gatewayClassName: istio   # istio gateway class 사용

  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "ticketing.test"  # 외부 도메인

    allowedRoutes:
      namespaces:
        from: All   # 다른 namespace의 route 허용